public class IfElse{
    public static void main(String []args){


        // If Statement
        int age = 22;
if (age >= 18) {
 System.out.println("Eligible for vote");
}

//IfElse Statement
int age = 16;
if (age >= 18) {
    System.out.println("Adult");
}
 else {
    System.out.println("Minor");
}


// Else-If Staterment
int marks = 75;

if (marks >= 90) {
    System.out.println("A+");
} 
else if (marks >= 75) {
    System.out.println("A");
} 
else if (marks >= 60) {
    System.out.println("B");
}
 else {
    System.out.println("C");
}
}
}